### ISSUE TITLE
Trigger a button (not toggle)

### ISSUE THREAD

**Issue by AxelRHD** [ioBroker/ioBroker.lovelace#109]
Is it possible to trigger a button ( = fire an event) without toggling the state? Tip-action for calling a service only seams to work with Home Assistant but not ioBroker.

Would be great to implement (or document) it.

**Comment by Garfonso** [comment]
I'll take the "document it" option, if I find the time.. ;-)

service_calls should mostly work similar to Home Assistant. If you have an example of a the service_call that you struggle with, I'll look a bit more into it.
I'm not sure if this is required in Home Assistant, but in ioBroker we need the entity_id in service data, i.e. something like this:
```
 action: call-service
  service: trigger
  service_data:
    entity_id: plug.triggerMePlease
```
This should then always set the associated object in ioBroker to true.

**Comment by AxelRHD** [comment]
Thank you for the very fast response. With your input I got it up and running.

Little excerpt:

```yml
type: horizontal-stack
cards:
  - type: entity-button
    entity: script.lovelace_homematic_thermostat_bad_SET_ECO
    name: ECO
    icon: "mdi:arrow-down-bold"
    tap_action:
      action: call-service
      service: script.turn_on
      service_data:
        entity_id: script.lovelace_homematic_thermostat_bad_SET_ECO
```
