### ISSUE TITLE
Theme does not work correctly

### ISSUE THREAD

**Issue by dontobi** [ioBroker/ioBroker.lovelace#151]
**Describe the bug**  
I have recently updated to version 1.4.2. Since then, some devices (Poco F2 Pro and a notebook with Windows 10) show me the default theme, although I have selected my own theme (as default theme and dark default theme).

I would appreciate it if you could include a choice to select whether you want to use only one theme or a changing theme.

**To Reproduce**  
Devices with DARK mode set will display the set theme. Devices with DARK Mode turned off will display the default theme even though it is not set.

**Expected behavior**  
You should always see your own theme, because it is set in the adapter settings.

**Screenshots & Logfiles**  
![Screenshot_2021-01-12-08-46-54-188_com.android.chrome.jpg](https://user-images.githubusercontent.com/19261667/104285387-d7b87000-54b3-11eb-810d-f717d06312e6.jpg)

**Versions:**  
 - Adapter version: 1.4.2
 - JS-Controller version: 3.2.6 (also tested with 3.1.6)
 - Node version: 12.20.0
 - Operating system: ioBroker Docker Container dein buanet

**Additional context**  
```
slate:
  # Main colors
  primary-color: '#2196f3'
  accent-color: '#E45E65'
  dark-primary-color: '#2196f3'
  light-primary-color: '#2196f3'
  # Text colors
  primary-text-color: '#FFFFFF'
  text-primary-color: 'var(--primary-text-color)'
  secondary-text-color: '#2196f3'
  disabled-text-color: '#777777'
  label-badge-border-color: 'green'
  # Sidebar
  sidebar-icon-color: '#777777'
  # Background colors
  primary-background-color: '#222222'
  secondary-background-color: '#222222'
  divider-color: 'rgba(0, 0, 0, .12)'
  table-row-background-color: '#292929'
  table-row-alternative-background-color: '#292929'
  # Nav Menu
  paper-listbox-color: '#777777'
  paper-listbox-background-color: '#141414'
  paper-grey-50: 'var(--primary-text-color)'
  paper-grey-200: '#222222'
  # Paper card
  paper-card-header-color: '#2196f3'
  paper-card-background-color: '#292929'
  paper-dialog-background-color: '#292929'
  paper-item-icon-color: 'var(--primary-text-color)'
  paper-item-icon-active-color: '#2196f3'
  paper-item-icon_-_color: 'green'
  paper-item-selected_-_background-color: '#292929'
  paper-tabs-selection-bar-color: 'green'
  # Labels
  label-badge-red: 'var(--primary-color)'
  label-badge-text-color: 'var(--primary-text-color)'
  label-badge-background-color: '#222222'
  # Switches
  paper-toggle-button-checked-button-color: '#2196f3'
  paper-toggle-button-checked-bar-color: '#2196f3'
  paper-toggle-button-checked-ink-color: '#2196f3'
  paper-toggle-button-unchecked-button-color: 'var(--disabled-text-color)'
  paper-toggle-button-unchecked-bar-color: 'var(--disabled-text-color)'
  paper-toggle-button-unchecked-ink-color: 'var(--disabled-text-color)'
  switch-checked-color: 'var(--paper-toggle-button-checked-button-color)'
  switch-unchecked-color: 'var(--disabled-text-color)'
  switch-unchecked-button-color: 'var(--disabled-text-color)'
  switch-unchecked-track-color: 'var(--disabled-text-color)'
  # Sliders
  paper-slider-knob-color: '#2196f3'
  paper-slider-knob-start-color: '#2196f3'
  paper-slider-pin-color: '#2196f3'
  paper-slider-active-color: '#2196f3'
  paper-slider-container-color: 'linear-gradient(var(--primary-background-color), var(--secondary-background-color)) no-repeat'
  paper-slider-secondary-color: 'var(--secondary-background-color)'
  paper-slider-disabled-active-color: 'var(--disabled-text-color)'
  paper-slider-disabled-secondary-color: 'var(--disabled-text-color)'
  # Google colors
  google-red-500: '#b93829'
  google-green-500: '#2196f3'
  # Changes to fix history/logbook menus
  lumo-primary-text-color: '#2196f3'
  lumo-secondary-text-color: '#2196f3'
  lumo-primary-color: '#2196f3'
  # Calendar day numbers
  lumo-body-text-color: '#2196f3'
  # Calendar/Date-Picker Background
  lumo-base-color: '#222222'
  # Month/Year header
  lumo-header-text-color: 'var(--lumo-body-text-color)'
  # DayOfWeek Header
  lumo-tertiary-text-color: 'var(--lumo-body-text-color)'
  lumo-shade: '#222222'
  lumo-shade-90pct: 'rgba(34, 34, 34, .9)'
  lumo-shade-80pct: 'rgba(34, 34, 34, .8)'
  lumo-shade-70pct: 'rgba(34, 34, 34, .7)'
  lumo-shade-60pct: 'rgba(34, 34, 34, .6)'
  lumo-shade-50pct: 'rgba(34, 34, 34, .5)'
  lumo-shade-40pct: 'rgba(34, 34, 34, .4)'
  lumo-shade-30pct: 'rgba(34, 34, 34, .3)'
  lumo-shade-20pct: 'rgba(34, 34, 34, .2)'
  lumo-shade-10pct: 'rgba(34, 34, 34, .1)'
  lumo-shade-5pct: 'rgba(34, 34, 34, .05)'
  lumo-tint-5pct: '#222222'
  # fix for device configuration screen
  card-background-color: "var(--paper-card-background-color)"
  # Fix for Person Device Chooser - thanks to vajonam!
  material-background-color: "var(--paper-listbox-background-color)"
  material-secondary-background-color: '#222222'
  material-body-text-color: '#FFFFFF'
  # simple-thermostat buttons
  st-mode-background: 'var(--primary-background-color)'
```
