### ISSUE TITLE
Tab-Bar never fades out

### ISSUE THREAD

**Issue by M1r0o** [ioBroker/ioBroker.lovelace#152]
Hi there,
I´m using the Lovelace Adapter latest release (1.4.2). 

Since updating, the tab-Bar never dissapears. 
In the former used version, the tab-bar dissapears when clicking or tabbing on a card.

I´ve done a screenshot to show it better: <a href="https://ibb.co/4KbcPF3"><img src="https://i.ibb.co/4KbcPF3/Bildschirmfoto-2021-01-15-um-15-06-07.png" alt="Bildschirmfoto-2021-01-15-um-15-06-07" border="0"></a>

Is there any possibility to let the tab-bar fade out?

**Comment by Garfonso** [comment]
For the record: 
issue is that Lovelace UI itself changed its header a lot. So this is now different. This also affects other projects, like Custom Header mod and so on... see for example this discussion: 
https://community.home-assistant.io/t/custom-header/155399/1100

You can completely hide the toolbar by adding card-mod custom card and adding this code to your theme:
```yaml
MYTHEME:
  # theme values here...
  card-mod-theme: MYTHEME
  card-mod-root: |
    app-toolbar {
      display: none;
    }
```

For example for `synthwave` theme:
![card-mod-no-header](https://user-images.githubusercontent.com/620860/105084778-2313e500-5a97-11eb-91d5-8ac535fb9ad8.JPG)
