### ISSUE TITLE
100% bedeutung für Rolladen/Jalousie

### ISSUE THREAD

**Issue by ElRedef** [ioBroker/ioBroker.lovelace#259]
Hallo,

ich benutze nun zum ersten mal sowohl die 'Slider' für Rolladen als auch die 'Auf/Ab Pfeile" gleichzeitig. 
Bisher hatte ich immer nur eines in Benutzung und habe mit der Checkbox in den Einstellungen die Richtung gedreht. 

### Wie ich denke dass es funktionieren sollte:
_Slider rechts_ ist  `zu` und _Pfeil nach unten_ ist `zu`. 
Oder anders: _Slider rechts_ und _Pfeil nach unten_ sollte die gleiche Einstellung/Zahl ergeben. 

### Was ich beobachte:
Die Zahl ist die Zahl im Positionsobjekt im Objektbaum nach ausführen der Aktion
(in Klammern die physische Bewegung meines Rolladen, hier eigentlich nicht notwendig)
[Eckige Klammer = meine Bewertung für `auf`, die Bewertung für `zu `ist dann klar  ]

**Haken 100%  nicht gesetzt -> Bedeutung: Rolladen bei 100% geöffnet**
Slider ganz nach rechts:  100% (fährt nach unten) [Slider rechts bedeutet zu, 100% bedeutet aber offen]
Slider ganz nach links: 0% (fährt nach oben)
Nach oben: 100%  (fährt nach unten) [das passt]
Nach unten: 0% (fährt nach oben)

**Haken 100% gesetzt -> Bedeutung: Rolladen 100% = geschlossen**
Slider ganz nach rechts:  0% (fährt nach oben) [nach rechts bedeutet zu, 0% bedeutet offen]
Slider ganz nach links: 100% (fährt nach unten)
Nach oben: 0% (fährt nach oben) [das passt]
Nach unten: 100% (fährt nach unten)

**Comment by Garfonso** [comment]
Beziehen sich deine Slider Stellungen auf das cover entity oder das (aus rückwärtskompatibilitätsgründen zusätzlich angelegte) input_number entity?
Da hab ich gerade festgestellt, dass die sich anscheinend unterschiedlich verhalten, wenn der Haken gesetzt ist zumindest. Was aber nicht überraschend ist, da der input_number einfach nur die % Zahl angibt ohne weitere Behandlung.

Sonst ist es in Lovelace/HASS wohl so gedacht, dass Slider nach ganz rechts = 100% = offen ist. Daran kann ich erstmal nichts ändern (insbesondere der slider im more-info fenster von einem cover-entity zeigt das deutlich -> rechts ist 100%, was im HASS Universum "offen" heißt). 

Der Haken mit 100% = zu, dreht dabei nur die Werte rum, die in ioBroker ankommen / von diesem gemeldet werden. Ob du den setzt oder nicht, musst du danach entscheiden, was deine Rolladen für "zu" haben wollen. Wenn das 100% ist, dann solltest du ihn setzen, wenn es 0% ist, dann brauchst du die Konvertierung nicht.

Gut möglich, dass das schlecht beschrieben ist.

**Comment by ElRedef** [comment]
Die Entity wird wie folgt generiert:

```
type: entities
entities:
  - entity: light.Kinderzimmer2
    name: Licht
  - entity: cover.Kind_2_Links
    name: Rolladen Links
  - entity: cover.Kind_2_Rechts
    name: Rolladen Rechts
  - entity: sensor.KiZi2_Temperatur
title: Kind2
```
Wenn man dann auf das Rolladensymbol klickt erhält man eine Anzeige mit Auf/Ab Pfeilen und einem Slider. 
Das sieht dann wie folgt aus (einmal mit und einmal ohne gesetztem Haken)

![Rolladen_haken_nicht_gesetzt](https://user-images.githubusercontent.com/66745270/134771509-a0711b3a-e675-43c4-ae5b-fb3943f59fad.jpg)
![Rolladen_haken_gesetzt](https://user-images.githubusercontent.com/66745270/134771510-85d767a9-8ba8-4ce9-b0a1-ff1b8db52e35.jpg)

Rot = Die Werte die geschrieben werden
Grün = Meine Bewertung bzw. mein Sollwert. 


Wenn der Haken einfach die Werte rum dreht die in den Objektbaum geschrieben werden dann ist es wohl so dass beim Links/Rechts vertauschen auch immer Oben/Unten vertauscht wird. 

Somit gibt es mit dieser Art der Lösung leider kein Szenario das sagt:
Pfeil runter = runter
Slider rechts = runter

**Comment by Garfonso** [comment]
Ja, das ist more-info vom cover entity. Und rechts sagt der Slider 100%. Und HASS sagt ganz klar 100% = offen, z.B. [hier](https://github.com/home-assistant/core/blob/dev/homeassistant/components/cover/__init__.py#L194). Insofern ist es tatsächlich so gedacht, dass der slider nach ganz rechts = ganz offen bedeutet. 

Gleichzeitig bedeutet "rauf" natürlich immer "rauf" und "runter" immer "runter". Die Invertierung ist, wie gesagt, nur dafür da, damit lovelace auch ioBroker Rolladen steuern kann die in der HomeAssitant Welt (und mittlerweile auch in der ioBroker Welt) "falsch" sind und bei 0% offen und nicht zu. 

Man könnte natürlich noch versuchen eine weitere Option hinzuzufügen... aber ehrlich gesagt, raucht mir auch so der Kopf jedes mal, wenn ich mir das angucke, eine weitere Option würde die vorhandenen zwei Fälle an 4 Positionen auf 4 Fälle an 8 Positionen erweitern... urgs... da würde ich dich lieber an HomeAssistant/Frontend weiterleiten ;-)

Ich empfehle das more-info halt so zu nehmen, wie es ist und in einem Elements das cover.Kind_2_Links und zusätzlich input_number.Kind_2_Links hinzuzufügen. Oder alternativ mit der [`custom:slider-entity-row`](https://github.com/thomasloven/lovelace-slider-entity-row) zu arbeiten (oder eine andere custom Karte zu suchen -> das ist der präferierte Weg die Oberfläche anzupassen, wenn einem der Standard nicht gefällt - wobei die slider-entity-row ebenfalls "rechts" = geschlossen setzt, wie man auch im Beispiel sehen kann).

**Comment by Garfonso** [comment]
Ich hätte noch einen Vorschlag. Du hast ein ioBroker-Rollade nur mit level, oder? Du könntest ein Alias Gerät anlegen, bei dem du OPEN und CLOSE noch hinzufügst und da jeweils im RAW Objekt write: 0 bzw. write: 100 einfügst. Dann würden die Rauf/Runter Knöpfe immer die Open/Close aliase nutzen und immer 0/100 schreiben und der Slider bedient dann level, denn du entweder mit dem Alias oder dem Haken in den Instanzeinstellungen verändern kannst, wie es dir gefällt. 

Hab das gerade mal mit dem neuen Devices Adapter ausprobiert, da geht das sogar jetzt alles in der UI:
So das Alias-Gerät anlegen:
![lovelace-cover-alias](https://user-images.githubusercontent.com/620860/134798005-c87fab10-2deb-4cff-a28c-ba1044a444c6.JPG)
Und so "write" einstellen:
![lovelace-cover-alias-write](https://user-images.githubusercontent.com/620860/134798022-cae20edc-34b2-4028-8e96-dd73881a64b3.JPG)

**Comment by ElRedef** [comment]
Wow, das tut. Super Idee.

Mein Rolladen hat ein Auf/Ab Element. Aber nur ein kombiniertes. True = auf ; False = ab. 
Deswegen konnte ich bis jetzt nichts damit machen. 
Aber mit der Art oben kann ich jetzt die richtigen Werte setzen.

Super! Danke!

**Comment by ElRedef** [comment]
Nachtrag:
Es tut doch nicht zu 100%. 

Wenn der Rolladen am Anschlag ist (Also 0% oder 100%) wird der entsprechende Auf/Ab Pfeil ausgeblendet. Also wenn man ganz oben ist kann man nicht noch weiter nach oben fahren.

Wenn ich nun über diese Methode oben/unten vertauschen wird leider der falsche Pfeil ausgeblendet ;-(

**Comment by Garfonso** [comment]
Ja... wenn der Rolladen komplett oben ist, kann man ihn nicht weiter nach oben fahren. Das ist richtig... warum willst du weiter nach oben fahren, wenn er komplett oben ist?

**Comment by ElRedef** [comment]
Sorry da hab ich wohl ein Detail vergessen . Durch das Vertauschen kann man ihn nicht mehr Runterfahren wenn er oben ist. Weil die falsche Richtung ausgeblendet wird.

**Comment by Garfonso** [comment]
Ja, es bleibt dabei, dass du den Adapter nicht anlügen solltest 😄  bzw. damit leben musst, dass in HomeAssistant grundsätzlich gilt 100% = offen.

Meine Rolladen sind auch "falschrum" und ich mag die Idee, dass 100% = offen ist, nicht... 

Ich kann dir meine Konfiguration einmal zeigen:
![Rolladen-konfiguration](https://user-images.githubusercontent.com/620860/142828861-8e129a9b-29b7-4f78-ad95-7dd02aa4f9b0.JPG)

Das ist eine "Elemente" Karte in der jeweils (neben ein paar Knöpfen, die mittels  skripten in jedem raum zu festgelegten Werten fahren) für jeden Rolladen zwei Zeilen sind, einmal einfach das cover, was zu den drei Knöpfen führt und einmal als input_number, was zu dem Slider führt (alternative wäre die slider-entity-row Karte zu nehmen, der input_slider wird aber aus Kompatibilitätsgründen noch erstellt und das wird auch so bleiben, denke ich). 

Hier der yaml Code dazu (die Knopfreihen hab ich rausgenommen):
````
type: entities
entities:
  - type: section
    label: Schlafzimmer
  - entity: cover.Rolladen_Schlafzimmer_Hof
    icon: mdi:window-shutter
    name: Schlafzimmer Hof
  - entity: input_number.Rolladen_Schlafzimmer_Hof
    name: ' '
    icon: mdi:window-shutter
  - entity: cover.Rolladen_Schlafzimmer_Strasse
    icon: mdi:window-shutter
    name: Schlafzimmer Straße
  - entity: input_number.Rolladen_Schlafzimmer_Strasse
    icon: mdi:window-shutter
    name: ' '
  - type: section
  - entity: cover.Rolladen_Fitness
    icon: mdi:window-shutter
    name: Fitness
  - entity: input_number.Rolladen_Fitness
    name: ' '
    icon: mdi:window-shutter
  - type: section
  - entity: cover.Rolladen_Bad_Oben
    name: Badzimmer
  - entity: input_number.Rolladen_Bad_Oben
    icon: mdi:window-shutter
    full_row: true
    name: ' '
title: Dachgeschoss
show_header_toggle: false

````

Ich arbeite geraden an unterstützung der browser-mod Karte, da kann man sowas auch noch mit popups basteln (popups müssten schon gehen).
