### ISSUE TITLE
Support auto-entities card

### ISSUE THREAD

**Issue by Garfonso** [ioBroker/ioBroker.lovelace#277]
Problem: adapter does not subscribe states, because card does not have entity / entities fields with entity_ids but allows filter / regex with entity ids. 

Configuration example ( https://forum.iobroker.net/post/697157 ):
```
type: custom:auto-entities
card:
  type: entities
  title: Aktuelle Stromverbraucher
filter:
  include:
    - entity_id: /sensor.*_Power/
      options:
        icon: mdi:flash-circle
  exclude:
    - state: 0
show_empty: false
sort:
  method: state
  reverse: true
  numeric: true
```

Todo: what other filters are possible?

**Comment by chah90** [comment]
Workaround I currently use to overcome this problem (perhaps this might be useful for someone until the behavior is optimized):

Create a hidden card to list all entities that I want to use in auto-entities:
```
type: conditional
conditions:
  - entity: switch.lovelace_show_hidden
    state: 'on'
card:
  type: entities
  entities:
    - entity: sensor.my_first_entity
    - entity: sensor.my_second_entity
  title: Hidden entities for auto-entities 
```

I configured a `switch.lovelace_show_hidden` entity that is always false. Of course, you can use an existing entity with an impossible condition if you like (e.g. humidity sensor with value of 0).
