### ISSUE TITLE
Removal of 'Bell' an 'Microphone'

### ISSUE THREAD

**Issue by ElRedef** [ioBroker/ioBroker.lovelace#390]
**Is your feature request related to a problem? Please describe.**
We use lovelace mainly on mobile phones. So two more icons would save a lot of scrolling.
Also my wife is using only the symbols which are visible without scrolling. 
Bell and microphone aren't used, so it would be good to use this screen space for additional views. 

**Describe the solution you'd like**
There is already a setting "Werkzeugleiste verstecken' under "Themes". Would be good if there would be simílar options for bell and microphone.

**Comment by dontobi** [comment]
I would rather leave the icons where they are and have another suggestion. Because if you hide the two icons, you would only get space for 2 more pages. If you have more than 8 pages set up, you still have to scroll.

My suggestion:
I would rather have the individual pages displayed in a side menu (hamburger menu).

**Comment by ElRedef** [comment]
But how to make a hamburger menu?

**Comment by Garfonso** [comment]
You can use card_mod / theme to hide the toolbar. The same is probably possible with the two icons.

Also, more changes there will make frontend updates harder, so this is to be carefully considered...

**Comment by ElRedef** [comment]
Thank you for the hint. 


Tested the following:


_MyTheme:
  card-mod-theme: MyTheme
  card-mod-root-yaml: |
    paper-tabs$: |
       app-toolbar:not([class="edit-mode"]) mwc-icon-button[label] {
        display: none; 
      }_

(Of course with correct yaml indentation, no idea why this is displayed wrong here)
It removes the microphones on firefox.
It doesn't work on chrome ( and edge). Unfortunately chrome is the target. 

Testet to remove the app-toolbar. This worked with firefox and chrome.

Any hints/suggestions?

Best regards

Johannes

**Comment by agross** [comment]
@ElRedef 

Fence code with 3 backticks: (```)

```
This
  is indented with 2 spaces
```

**Comment by Garfonso** [comment]
> Thank you for the hint.
> 
> Tested the following:
> 
> ```
> _MyTheme:
>   card-mod-theme: MyTheme
>   card-mod-root-yaml: |
>     paper-tabs$: |
>        app-toolbar:not([class="edit-mode"]) mwc-icon-button[label] {
>         display: none; 
>       }_
> ```
> 
> ( Corrected: Of course with correct yaml indentation, no idea why this is displayed wrong here) It removes the microphones on firefox. It doesn't work on chrome ( and edge). Unfortunately chrome is the target.
> 
> Testet to remove the app-toolbar. This worked with firefox and chrome.
> 
> Any hints/suggestions?
> 
> Best regards
> 
> Johannes

Hm.. to hide the complet toolbar, this code works:
```
card-mod-theme: THEMENAME
  card-mod-root: |
  app-toolbar {
    display: none;
  }
```
Of course, that is not what you want, because it will also hide the tabs for the pages... but maybe you can investigate further from that?

**Comment by pafade89** [comment]
Hi,
the following code worked for me. Important to note is that you do **not** open lovelace in editor mode. 

Correct is:
`http://IP:PORT/lovelace/default_view`

without:
`?toolbar=true`

Also in Chrome I could test it successfully.

```
  card-mod-theme: "name of your theme"
  card-mod-root: |
    app-toolbar:not([class="edit-mode"]) mwc-icon-button[label] {
      display: none; 
    }
```

Cheers P

**Comment by agross** [comment]
> ```
> card-mod-theme: "name of your theme"
>   card-mod-root: |
>     app-toolbar:not([class="edit-mode"]) mwc-icon-button[label] {
>       display: none; 
>     }
> ```

Where should that snippet be inserted?

**Comment by pafade89** [comment]
Hi @agross,

you have to insert the snippet in your lovelace instanz settings under the theme tab. 

Does that help you?

Cheers P

**Comment by agross** [comment]
Hm, that does not work here.

<details>

```yaml
# My Home Assistant Config files: https://github.com/JuanMTech/Home_Assistant_files

Green Dark Mode:
  # light-green: "#466931"
  light-green: "#5c903c"
  dark-green: "#345025"
  light-gray: "#b8babb"
  dark-gray: "#636466"

  # Header.
  app-header-background-color: var(--dark-green)
  app-header-text-color: var(--light-gray)

  # Main interface colors.
  primary-color: var(--light-green)
  light-primary-color: var(--primary-color)
  primary-background-color: var(--light-green)
  secondary-background-color: "#252629" # Popups.
  divider-color: var(--primary-background-color)
  accent-color: var(--primary-color)

  # Text.
  primary-text-color: var(--light-gray)
  secondary-text-color: var(--light-gray)
  text-primary-color: "#ffffff"
  disabled-text-color: var(--dark-gray)

  # Sidebar menu.
  sidebar-icon-color: var(--app-header-text-color)
  sidebar-text-color: '#b8babb'
  sidebar-background-color: "#1C1D21"
  sidebar-selected-background-color: var(--primary-background-color)
  sidebar-selected-icon-color: var(--light-green)
  sidebar-selected-text-color: var(--sidebar-selected-icon-color))

  # States and badges.
  state-icon-color: var(--light-gray)
  state-icon-active-color: var(--light-green)
  state-icon-unavailable-color: var(--disabled-text-color)

  # Sliders.
  paper-slider-knob-color: var(--light-green)
  paper-slider-knob-start-color: var(--paper-slider-knob-color)
  paper-slider-pin-color: var(--paper-slider-knob-color)
  paper-slider-active-color: var(--paper-slider-knob-color)
  paper-slider-secondary-color: var(--light-primary-color)

  # Labels.
  label-badge-background-color: "#202124"
  label-badge-text-color: var(--light-gray)
  label-badge-red: "#D06568"
  label-badge-green: "#80C884"
  label-badge-blue: "#5F9BEA"
  label-badge-yellow: "#DFC271"
  label-badge-gray: "#5F6267"

  # Cards.
  card-background-color: "#252629"
  ha-card-border-radius: "10px"
  ha-card-box-shadow: 0px
  paper-dialog-background-color: var(--card-background-color)
  paper-listbox-background-color: "#1C1D21"
  paper-card-background-color: var(--card-background-color)

  # Switches.
  switch-checked-button-color: var(--light-green)
  switch-checked-track-color: var(--dark-green)
  switch-unchecked-button-color: var(--dark-gray)
  switch-unchecked-track-color: var(--dark-gray)

  # Toggles.
  paper-toggle-button-checked-button-color: var(--switch-checked-button-color)
  paper-toggle-button-checked-bar-color: var(--switch-checked-track-color)
  paper-toggle-button-unchecked-button-color: var(--switch-unchecked-button-color)
  paper-toggle-button-unchecked-bar-color: var(--switch-unchecked-track-color)

  # Tables.
  table-row-background-color: var(--primary-background-color)
  table-row-alternative-background-color: var(--secondary-background-color)
  data-table-background-color: var(--primary-background-color)

  # Inputs.
  input-fill-color: var(--secondary-background-color)
  input-dropdown-icon-color: var(--secondary-text-color)
  input-ink-color: var(--primary-text-color)
  input-label-ink-color: var(--secondary-text-color)
  input-idle-line-color: var(--primary-text-color)
  input-hover-line-color: var(--accent-color)

  # Dropdowns.
  material-background-color: var(--secondary-background-color)
  material-secondary-background-color: var(--primary-background-color)
  mdc-theme-surface: var(--secondary-background-color)

  # HACS.
  hacs-chip-background-color: var(--primary-color)

  # Code.
  markdown-code-background-color: var(--card-background-color)
  code-editor-background-color: var(--card-background-color)

card-mod-theme: Green Dark Mode
card-mod-root: |
  app-toolbar:not([class="edit-mode"]) mwc-icon-button[label] {
    display: none;
  }

```

</details>
