### ISSUE TITLE
individual1: und individual2: werden von power-flow-card-plus bei IOBroker nicht angezeigt

### ISSUE THREAD

**Issue by RALFISBORN** [ioBroker/ioBroker.lovelace#483]
Hallo,

wie bereits hier in dem Issue von power-flow-card-plus beschrieben, werden die individual1 und individual2 bei IOBroker Lovelace nicht angezeigt:
[(https://github.com/flixlix/power-flow-card-plus/issues/383)]

Problem besteht bei der aktuellen Stable Version als auch der aktuellen 4.1.0.

Kann das bitte gefixt werden?
Vielen Dank

**Comment by Garfonso** [comment]
Versuch bitte mal den entity, den du bei "individual1" oder so eingeben hast irgendwo anders in der UI zu nutzen, zB in einer Sensor oder Elemente Karre.

Kommt dann der Wert bzw wird aktualisiert?

Ansonsten: gibt es Unterschiede zwischen den entities? Was passiert, wenn du einen entity, der für irgendwas auf der Karte funktioniert auch als individual1 angibst, geht es dann?

Kommen im Log Fehlermeldungen? (iobroker log und Browser Konsole)

Es kann vielleicht gefixt werden, hängt aber davon ab, wie viel die User, die sich das wünschen, mithelfen. 🙂 Aktuell habe ich keine Idee dazu.

**Comment by RALFISBORN** [comment]
Ja, der Wert wird in anderen Karten (auch in der Power Flow Karte bei z.B. Grid/Consumption) einwandfrei angezeigt.

Mir sind jetzt beim probieren mehrere Sachen aufgefallen, welche nicht gehen.
Ich habe folgende Karte erstellt:
![image](https://github.com/ioBroker/ioBroker.lovelace/assets/47441243/e33907a5-baf7-4b78-bc5b-a5ee687d224c)
Wobei die PV2 als "fossil_fuel_percentage" eingebunden ist.
![image](https://github.com/ioBroker/ioBroker.lovelace/assets/47441243/901085cb-7bcb-4150-b42a-b4f7de1d7fae)

Der komplette YAML Code sieht wie folgt aus:
```
type: custom:power-flow-card-plus
entities:
  grid:
    entity:
      consumption: sensor.Elektro_Bezug
      production: sensor.Elektro_Einspeisung
      display_state: two_way
      color_circle: true
  solar:
    entity: sensor.Elektro_Solar
    name: DachPV
  home:
    entity: sensor.Elektro_Statistik_Verbrauch
    name: Homebase
    override_state: true
  battery:
    name: Batterie
    icon: mdi:fuel-cell
    entity:
      consumption: sensor.Elektro_BatterieIImport
      production: sensor.Elektro_BatterieExport
  fossil_fuel_percentage:
    entity: sensor.Elektro_Solar2
    name: PV2
    color_icon: true
    display_zero: true
    color: '#FBCC2F'
    icon: mdi:solar-power-variant
clickable_entities: true
display_zero_lines: true
use_new_flow_rate_model: true
w_decimals: 0
kw_decimals: 1
min_flow_rate: 3
max_flow_rate: 6
max_expected_power: 2000
min_expected_power: 0.01
watt_threshold: 1000
transparency_zero_lines: 0
title: Aktueller elektrischer Verbrauch
```

Die einzelnen Werte sind jeweils als Sensor vom Typ "Energie" angelegt:
![image](https://github.com/ioBroker/ioBroker.lovelace/assets/47441243/109ea51b-db8e-4407-a4ad-a3cc5407c6ac)

Mir sind nun folgende Dinge aufgefallen, welche nicht funktionieren:
- Batterie consumption/production zeigen immer den Wert 0 an obwohl in der Variable in IOBroker ein Wert steht
- Fossil_Fuel_Percentage: Gleiches verhalten (immer Wert 0 obwohl in IOBroker nicht auf 0)
- Sobald "fossil_fuel_percentage" durch "individual1/2" ersetzt wird, wird das Symbol gar nicht mehr angezeigt:
![image](https://github.com/ioBroker/ioBroker.lovelace/assets/47441243/7bfa368d-05fd-4e6e-a745-b11841f49fc0)

Ich habe das ganze auch mit unterschiedlichen Browsern (Brave/Firefox) probiert.
Folgendes kommt in den Logs (ich hoffe das hilft das Problem zu fixen):

![image](https://github.com/ioBroker/ioBroker.lovelace/assets/47441243/804945ab-c601-44ab-b5a6-505e199675ad)
Consolen Log:
![image](https://github.com/ioBroker/ioBroker.lovelace/assets/47441243/c0ecafcc-f07d-468c-baca-4850ea647e57)
