### ISSUE TITLE
Person Entity

### ISSUE THREAD

**Issue by R1Snake** [ioBroker/ioBroker.lovelace#490]
Does anybody knows how i can create a person entity?

My target is to create a presence card with the image from the users i created in iobroker.

**Comment by Garfonso** [comment]
I, personally, use a binary_sensor entity for that (with device class set to "presence") and an entity_filter card with with the binary_sensors in there and image attributes, like:

```
type: entity-filter
entities:
  - entity: binary_sensor.users_user1_present
    show_last_changed: true
    image: /cards/Avatar-user1.jpg
  - entity: binary_sensor.users_user2_present
    show_last_changed: true
    image: /cards/Avatar-user2.png
```
