### ISSUE TITLE
Show MP4 Video from IOBroker Ring Adapter in Lovelace

### ISSUE THREAD

**Issue by Vippis2000** [ioBroker/ioBroker.lovelace#575]
Hi,

I'm trying to find a solution for showing MP4 videos, which are created from Ring adapter and stored in a file in /opt/iobroker/iobroker-data/files/ring.0/ folder structure.

I haven't found a proper solution. 

iframe not working

There are some solutions who use custom:html cards, but I can't get this card running in IOBroker lovelace.

https://community.home-assistant.io/t/play-mp4-files-or-stream-http-in-lovelace/218833

**Comment by Vippis2000** [comment]
This works:

```
type: custom:config-template-card
variables:
  URL: states['input_text.doorbell_625818110_Livestream_url'].state
entities:
  - input_text.doorbell_625818110_Livestream_url
card:
  type: iframe
  url: ${URL}
  aspect_ratio: 100%
  title: Letztes Live Video
```

You need template-card to read dynamic URL with new video files from DP 

`ring.0.doorbell_625818110.Livestream.url `

in my case
